api_version = "2025-10"
[[extensions]]
name = "Report Cards"
handle = "report-cards"
type = "ui_extension"
uid = "e7198085-4ce2-8443-e24c-e06457cbc27795de71bc"

# Only 1 target can be specified for each admin print action extension
[[extensions.targeting]]
module = "./src/PrintActionExtension.jsx"
target = "admin.order-details.print-action.render"

# Valid extension targets:

# - admin.order-details.print-action.render
# - admin.order-index.selection-print-action.render
# - admin.product-details.print-action.render
# - admin.product-index.selection-print-action.render
